#!/usr/bin/env bash
set -euo pipefail

cd /data/uavlab/multi-uav-pursuit2

export TIMESTAMP=20260415_034910
export PRED_MODE=tp_net
export IMITATION_USE_TP_NET=true
export BC_TP_MODEL_DIR=/data/uavlab/multi-uav-pursuit2/checkpoints/tp_supervised_20260415_005910/tp_only_20260415_010548.pt
export DAGGER_TP_WEIGHT="${BC_TP_MODEL_DIR}"

export START_FROM_SCRATCH=true
export RUN_COLLECT=true
export RUN_BC=true
export RUN_DAGGER=true

export V_DRONE_TEST=1.5
export V_PREY_TEST=1.5
export V_PREY_SCHEDULE=1.5
export EPISODE_LENGTH=1200
export EVAL_GPU=0

export GENERIC_BATCH_ENVS=1024
export NUM_WAVES=20
export GENERIC_SEED_BASE=20260415
export MIN_SUCCESS_STEPS=25
export DATASET_DTYPE=float16
export DATASET_NAME=expert2_step5_aligned_1024x20_${TIMESTAMP}

export BC_EPOCHS=30
export BC_BATCH_SIZE=4096
export BC_LR=0.0005
export BC_ACTION_MSE_COEF=1.0
export BC_LOG_PROB_COEF=0.0
export BC_AUX_WAYPOINT_COEF=0.02
export BC_AUX_ASSIGNMENT_COEF=0.05
export BC_FRONT_WEIGHT_ALPHA=0.5
export BC_KEEP_PREFIX_STEPS=-1
export BC_KEEP_SUFFIX_STEPS=64
export BC_EVAL_EVERY=1
export BC_N_EVAL=1024
export BC_EVAL_BATCH_ENVS=64
export BC_EVAL_SUCCESS_THRESHOLD=0.60
export BC_SAVE_TAG=expert2_step5_aligned_bc_1024x20_${TIMESTAMP}

export DAGGER_BATCH_ENVS=1024
export DAGGER_WAVES=10
export DAGGER_SEED_BASE=30360415
export DAGGER_LR=0.0001
export DAGGER_ACCUM_BATCH_SIZE=8192
export DAGGER_MIX_INIT=0.90
export DAGGER_MIX_FINAL=0.90
export DAGGER_ONLINE_SUCCESS_ONLY=true
export DAGGER_DEFER_ONLINE_UPDATES=true
export DAGGER_ONLINE_MIN_WAVE_CAPTURE_RATE=0.60
export DAGGER_ONLINE_RATIO_WARMUP_WAVES=10
export DAGGER_ONLINE_RATIO_INIT=0.10
export DAGGER_ONLINE_RATIO_STEP=0.05
export DAGGER_ONLINE_RATIO_MAX=0.40
export DAGGER_MIXED_UPDATES_PER_WAVE=0
export DAGGER_REPLAY_UPDATES_PER_WAVE=4
export DAGGER_REPLAY_BATCH_SIZE=4096
export DAGGER_REPLAY_FRONT_WEIGHT_ALPHA=0.5
export DAGGER_ONLINE_GOAL_WEIGHT_ALPHA=0.5
export DAGGER_ONLINE_DISAGREE_WEIGHT_ALPHA=2.0
export DAGGER_EVAL_EVERY=1
export DAGGER_N_EVAL=1024
export DAGGER_EVAL_BATCH_ENVS=64
export DAGGER_SAVE_TAG=expert2_step5_aligned_dagger_1024x10_${TIMESTAMP}
export DAGGER_DATASET_NAME=dagger_expert2_step5_aligned_1024x10_${TIMESTAMP}

export STRATEGY_VARIANT=expert2
export FORWARD_DIR_MODE=default
export EXPERT2_FRONT_LAYOUT=symmetric
export ENABLE_GOAL_MODE=false
export ENABLE_CLOSE_MODE=true
export ENABLE_RUSH_MODE=false
export EXPERT_INTERCEPT_PRED_STEP=5
export EXPERT_INTERCEPT_USE_DIRECT_PRED=false

bash scripts/run_expert2_actor_imitation_pipeline.sh
